### ISSUE TITLE
new users

### ISSUE THREAD

**Issue by bonnebulle** [tcoupin/rpi-proftpd#3]
hello
I understand how to mount volume contains /users folders but how to (or where to) put the {user password folder} file/infos ? In the configuration file ?
thanks for all

**Comment by tcoupin** [comment]
Just create files in /users directory and put user password and home in it.
Like
https://github.com/tcoupin/rpi-proftpd/blob/master/examples/users/users_example

**Comment by bonnebulle** [comment]
Thanks
the blob making the job
I was not sur how to name my users_list file !
(but yes, all files in my users folder is read.scanned for user parameters)
thanks again
